clear all
close all


set(figure(1),'units','normalized','position',[0.0031    0.0413    0.9938    0.0663],'menubar','none')


h=0.333;
L=0.6;
xo=0.2;
yo=0;

str=25;dip=25;rak=-25;



h_rak_nm=uicontrol('units','normalized',...
                 'style','text',...
                 'string','rake (deg)',...
                'position',[0,yo,xo,h]);
h_dip_nm=uicontrol('units','normalized',...
                 'style','text',...
                 'string','dip (deg)',...
                'position',[0,yo+h,xo,h]);
h_str_nm=uicontrol('units','normalized',...
                 'style','text',...
                 'string','azimuth (deg)',...                 
                'position',[0,yo+2*h,xo,h]);

            

h_rak_val=uicontrol('units','normalized',...
                 'style','edit',...
                 'string',num2str(rak),...
                'position',[xo+L,yo,xo,h]);
h_dip_val=uicontrol('units','normalized',...
                 'style','edit',...
                 'string',num2str(dip),...
                'position',[xo+L,yo+h,xo,h]);
h_str_val=uicontrol('units','normalized',...
                 'style','edit',...
                 'string',num2str(str),...                 
                'position',[xo+L,yo+2*h,xo,h]);

            

h_rak_slide=uicontrol('units','normalized',...
                 'style','slide',...
                 'min',-180,'max',180,...
                 'value',rak,...
                'position',[xo,yo,L,h],...
                'callback','rak=get(h_rak_slide,''value'');set(h_rak_val,''string'',num2str(rak));figure(2);sfoc3D(str,dip,rak);figure(3);sfoc2D(str,dip,rak);');
h_dip_slide=uicontrol('units','normalized',...
                 'style','slide',...
                 'min',0,'max',90,...
                 'value',dip,...                 
                'position',[xo,yo+h,L,h],...
                'callback','dip=get(h_dip_slide,''value'');set(h_dip_val,''string'',num2str(dip));figure(2);sfoc3D(str,dip,rak);figure(3);sfoc2D(str,dip,rak);');
h_str_slide=uicontrol('units','normalized',...
                 'style','slide',...
                 'min',0,'max',360,...
                 'value',str,...                                  
                'position',[xo,yo+2*h,L,h],...
                'callback','str=get(h_str_slide,''value'');set(h_str_val,''string'',num2str(str));figure(2);sfoc3D(str,dip,rak);figure(3);sfoc2D(str,dip,rak);');
            
            
set(h_rak_val,'callback','rak=str2num(get(h_rak_val,''string''));while(rak<-180);rak=rak+360;end;while(rak>180);rak=rak-360;end;set(h_rak_slide,''value'',rak);set(h_rak_val,''string'',num2str(rak));figure(2);sfoc3D(str,dip,rak);figure(3);sfoc2D(str,dip,rak);');
set(h_dip_val,'callback','diptmp=str2num(get(h_dip_val,''string''));if(diptmp>=0 && diptmp<=90);dip=diptmp;set(h_dip_slide,''value'',dip);end;set(h_dip_val,''string'',num2str(dip));figure(2);sfoc3D(str,dip,rak);figure(3);sfoc2D(str,dip,rak);');
set(h_str_val,'callback','str=str2num(get(h_str_val,''string''));while(str<0);str=str+360;end;while(str>360);str=str-360;end;set(h_str_slide,''value'',str);set(h_str_val,''string'',num2str(str));figure(2);sfoc3D(str,dip,rak);figure(3);sfoc2D(str,dip,rak);');


set(gcf,'color','white')


%definition des zones graphiques

set(figure(2),'units','normalized','position',[ 0.0016    0.1375    0.7172    0.7775])
sfoc3D(str,dip,rak);

set(figure(3),'units','normalized','position',[ 0.7242    0.1375    0.2734    0.3212],'menubar','none')
sfoc2D(str,dip,rak);








